name: BUILD

on:
  push:
  schedule:
    - cron:  '1 */8 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [clash-for-windows-chinese, joplin-appimage, netease-cloud-music]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: actions/upload-artifact@v2
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        
          
  uploadToOneDrive:      
    runs-on: ubuntu-latest
    if: always()
    needs: [buildAUR]

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        id: download
      
      - uses: ./create-db-and-upload-action
        with:
          RCLONE_ONEDRIVE_CLIENT_ID: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_ID }}
          RCLONE_ONEDRIVE_CLIENT_SECRET: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_SECRET }}
          RCLONE_ONEDRIVE_REGION: global
          RCLONE_ONEDRIVE_TOKEN: ${{ secrets.RCLONE_ONEDRIVE_TOKEN }}
          RCLONE_ONEDRIVE_DRIVE_ID: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_ID }}
          RCLONE_ONEDRIVE_DRIVE_TYPE: personal
          dest_path: /archrepo
          repo_name: vifly
#          gpg-privatekey: ${{ secrets.gpg_private_key }}
          local_path: ${{ steps.download.outputs.download-path }}